//
//  HomePageInteractor.swift
//  ViperCharts
//
//  Created Ps on 31/5/2561 BE.
//  Copyright © 2561 Ps. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePageInteractor: HomePageInteractorInputProtocol {

    weak var presenter: HomePageInteractorOutputProtocol?
}
