//
//  HomePageProtocols.swift
//  ViperCharts
//
//  Created Ps on 31/5/2561 BE.
//  Copyright © 2561 Ps. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomePageWireframeProtocol: class {

}
//MARK: Presenter -
protocol HomePagePresenterProtocol: class {

    var interactor: HomePageInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol HomePageInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol HomePageInteractorInputProtocol: class {

    var presenter: HomePageInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HomePageViewProtocol: class {

    var presenter: HomePagePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
