//
//  HomePageRouter.swift
//  ViperCharts
//
//  Created Ps on 31/5/2561 BE.
//  Copyright © 2561 Ps. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePageRouter: HomePageWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HomePageViewController(nibName: nil, bundle: nil)
        let interactor = HomePageInteractor()
        let router = HomePageRouter()
        let presenter = HomePagePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
