//
//  HomePagePresenter.swift
//  ViperCharts
//
//  Created Ps on 31/5/2561 BE.
//  Copyright © 2561 Ps. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePagePresenter: HomePagePresenterProtocol, HomePageInteractorOutputProtocol {

    weak private var view: HomePageViewProtocol?
    var interactor: HomePageInteractorInputProtocol?
    private let router: HomePageWireframeProtocol

    init(interface: HomePageViewProtocol, interactor: HomePageInteractorInputProtocol?, router: HomePageWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
